services:
  backend:
    build:
      context: .
      target: backend_app
    environment:
      BACKEND_PORT: ${BACKEND_PORT}

  resolver:
    build:
      context: .
      target: resolver
    environment:
      ADDRESS_OF_API: ${ADDRESS_OF_API}
      PING_API_ON_START: ${PING_API_ON_START}
      RESOLVER_PORT: ${RESOLVER_PORT}
    ports:
      - 127.0.0.1:${RESOLVER_PORT}:${RESOLVER_PORT}
    depends_on:
      - backend
